{{- if .Values.server.catalog.data | quote }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "presto.catalog" . }}
  labels:
    app: {{ template "presto.name" . }}
    chart: {{ template "presto.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  data:
{{ toYaml .Values.server.catalog.data | indent 4 }}
---
{{- end }}